version: '3'

tasks:
  default:
    desc: List available tasks
    cmds:
      - task --list

  cli:
    desc: Run cli
    cmds:
      - dotnet run --project AdventOfCode.Cli
  test:
    desc: Run tests
    cmds:
      - dotnet test
  benchmarks:
    desc: Run 'BenchmarkDotNet'
    cmds:
      - dotnet run -c Release --project AdventOfCode.Benchmarks
